#!/bin/bash
#1-store
cd $PROJECT_ROOT
if [ -z "${CRYPTOKEN}" ]; then
    echo "CRYPTOKEN is empty: $CRYPTOKEN"
    exit -1
fi
tar -cvJf _sensitive_datas/_sensitive_datas.tar.xz --exclude='.wrangler/tmp' bajarko-db/medusa_backup.sql apps/backend/static .vscode/settings.json .env apps/backend/.env apps/barrio/.env apps/vendor-panel/.env apps/motiharu/.env
openssl aes-256-cbc -base64 -md sha256 -pass pass:"$CRYPTOKEN" -in _sensitive_datas/_sensitive_datas.tar.xz -out _sensitive_datas/_sensitive_datas.tar.xz.enc
#3-delete 
rm _sensitive_datas/_sensitive_datas.tar.xz

echo "CRYPTED with 'openssl aes-256-cbc -base64 -md sha256 -pass pass:\"$CRYPTOKEN\"'"